### ISSUE TITLE
Add features: task 3

### ISSUE THREAD

**Issue by HalfSealHalfCat** [Ponamarev/Infa_2020_Ponamarev#1]
In [task 3](https://github.com/Ponamarev/Infa_2020_Ponamarev/tree/master/Lab3)

1. Create at least 3 aliens of different colours, transparency and shapes of arms/legs.
2. The same for its spaceships.
3. Rename files such that it will reflect the content and purpose.
4. Optionally animate some objects.

**Comment by Ponamarev** [comment]
Реализована возможность менять цвет, прозрачность, размеры, двигать объекты.
Сделано больше НЛО и Ино.
Переименован файл с Ино. Теперь старый файл зовется Ino_Old.py, а новый Ino_NEW.py
К несчастью, я пока не сделал анимацию

**Comment by Ponamarev** [comment]
Сделал анимацию для лабы3.
В качестве анимации сделано управление НЛО.
Его можно сделать прозрачным, включить луч захвата или переместить в просранстве.

**Comment by Ponamarev** [comment]
Сделана лаба4. Отправлен рефакторинг в репозиторий Светы

**Comment by Ponamarev** [comment]
Сделана вторая механика игры для лабы номер 5

**Comment by Ponamarev** [comment]
Добавлены звуки, комментарии, пасхалка
